export const SELCTION_MODE = {
    DEFAULT: "DEFAULT",
    FUSTUM: "FUSTUM",
    CLOUND_MARKUP: "CLOUND_MARKUP",
    ARROW_MARKUP: "ARROW_MARKUP",
    LINE_MARKUP: "LINE_MARKUP",
    DRAW_MARKUP: "DRAW_MARKUP",
    TEXT_MARKUP: "TEXT_MARKUP",
  }